services:
  redis:
    image: redis:alpine
    networks:
      - webnet


  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d  # Nginx config files
      - ./staticfiles:/static             # Static files collected by Django
      - ./media:/media
    depends_on:
      - chatapp
    networks:
      - webnet


  chatapp:
    build: .
    command: ["/bin/bash", "-c",
    "python3 manage.py makemigrations && \
    python3 manage.py migrate && \
    python manage.py runscript create_superuser && \
    python manage.py runscript create_randomusers && \
    python3 manage.py collectstatic --noinput && daphne -b 0.0.0.0 -p 8000 chatserver.asgi:application"]
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    networks:
      - webnet

  celery_worker:
    build: .
    command: ["celery", "-A", "chatserver", "worker", "--loglevel=info", "-E"]
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - chatapp
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
